petsadoption/pets_app/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from . import views 
from .views import AddPetView

urlpatterns = [
    path('', views.LandingPage.as_view() , name='landing'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('home/', views.home, name='home'),
    path('pets/', views.AllPets.as_view(), name='all-pets'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('my-pets/', views.MyPets.as_view(), name='my-pets'),
    path('adopt/<int:pet_id>/', views.adopt_pet, name='adopt_pet'),
    path('delete_request/<int:request_id>/', views.delete_adoption_request, name='delete_request'),
    path('toggle_fav/<int:pet_id>/', views.toggle_favorite, name='toggle_fav'),
    path('name-pet-inline/<int:adoption_id>/', views.name_pet_inline , name='name-pet-inline'),
    path('pet/<int:pet_id>/', views.pet_detail, name='pet-detail'),
    path('add-pet/', AddPetView.as_view(), name='add-pet'),

]

petsadoption/petsadoption/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),  
    path('', include('pets_app.urls'))  #to access all urls of pets_app
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petsadoption/pets_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

# My Models / tables.

User = get_user_model()   #built in user model

adoption_status_options=[
        ('Approved', 'Approved'),
        ('Pending', 'Pending'),
        ('Rejected', 'Rejected'),
    ]
availability_options=[
    ('Availabile' , 'Availabile'),
    ('Not Availabile' , 'Not Availabile')

]  

class Pets(models.Model):
    type=models.CharField(max_length=100)
    breed=models.CharField(max_length=100)
    photo=models.ImageField(upload_to='pet_photos/', blank=True, null=True)
    is_available=models.CharField(max_length=20, choices=availability_options, default='availabile')
    adoption_status = models.CharField(max_length=10, choices=adoption_status_options, default='pending')
    description = models.TextField(blank=True)
    pet_name = models.CharField(max_length=50, blank=True) 
    added_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    def __str__(self):   #to retrun the object name /// pet name // return object val as String
        return self.breed

class PetUser(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    pet=models.ForeignKey(Pets,on_delete=models.CASCADE)
    is_favorite=models.BooleanField(default=False)
    applied_at=models.DateField(auto_now=True)

    def __str__(self):   
        return f"{self.user.username} - {self.pet.type}"    


class AdoptionRequest(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    pet=models.ForeignKey(Pets,on_delete=models.CASCADE)
    adoption_status = models.CharField(max_length=10, choices=adoption_status_options, default='pending')
    requested_at=models.DateField(auto_now=True)
    care_plan=models.TextField()
    pet_name = models.CharField(max_length=100, blank=True, null=True) 

    def __str__(self):  
        return f"{self.user.username} - {self.pet.type}"  

petsadoption/pets_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import AdoptionRequest, Pets

class CustomUserCreationForm(UserCreationForm):
      # add extra field if you want

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "password1", "password2")  #feild to be shown in the form


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", 'first_name', 'last_name']


class AdoptionRequestForm(forms.ModelForm):
    class Meta:
        model = AdoptionRequest
        fields = ['care_plan']
        widgets = {
            'care_plan': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Describe how you’ll take care of the pet...'}),
        }

class PetNameForm(forms.ModelForm):
    class Meta:
        model = AdoptionRequest
        fields = ['pet_name']
        widgets = {
            'pet_name': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your pet’s new name'
            })
        }


class UserPetForm(forms.ModelForm):
    class Meta:
        model = Pets
        fields = ['pet_name', 'breed', 'type', 'photo', 'description']

petsadoption/pets_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomUserCreationForm, UserPetForm
from django.contrib.auth import login
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.views.generic import CreateView

#my Views
class LandingPage(View):   #this can be accessed only by new or logged out users
    template_name = "landing_page.html"

    def get(self, request):
        # If the user is logged in, redirect them to another page
        if request.user.is_authenticated:
            return redirect('home') 

        return render(request, self.template_name)
    
def signup(request):
    error_message = ''
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)  # built-in form for creating users
        if form.is_valid():
            user = form.save()  
            login(request, user)  # log the user in immediately after creating an account
            return redirect('home')  
        else:
            error_message = 'Invalid signup - try again'
    else:
        form = CustomUserCreationForm()  # empty form for GET request
    return render(request, 'registration/signup.html', {'form': form, 'error_message': error_message})
   
@login_required
def home(request):
    return render (request, 'home.html')

class AllPets(LoginRequiredMixin, ListView):
    model = Pets
    template_name = 'all_pets.html'
    context_object_name = 'pets'

    def get_queryset(self):
        # Only show public/admin pets
        queryset = Pets.objects.filter(added_by__isnull=True)
        pet_type = self.request.GET.get('pet_type')

        if pet_type and pet_type.lower() != "all":
            queryset = queryset.filter(type__iexact=pet_type)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['favorite_pet_ids'] = PetUser.objects.filter(
            user=self.request.user,
            is_favorite=True
        ).values_list('pet_id', flat=True)
        context['selected_type'] = self.request.GET.get('pet_type', '')
        context['types'] = Pets.objects.values_list('type', flat=True).distinct()
        return context

class Profile(LoginRequiredMixin, View):
    model=User
    template_name='profile.html'
    context_object_name='user'

    def get(self, request):
        form = UserEditForm(instance=request.user)
        requests = AdoptionRequest.objects.filter(user=request.user).order_by('-requested_at')
        return render(request, self.template_name, {
            'form': form,
            'user': request.user,
            'requests': requests  # pass requests to template
        })

    def post(self, request):
        form = UserEditForm(request.POST, instance=request.user)
        requests = AdoptionRequest.objects.filter(user=request.user).order_by('-requested_at')
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully!')
            return redirect('profile')
        return render(request, self.template_name, {
            'form': form,
            'user': request.user,
            'requests': requests
        })

class MyPets(LoginRequiredMixin, TemplateView):
    template_name = 'my_pets.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        # Adopted pets (approved requests)
        context['adopted_pets'] = Pets.objects.filter(
            adoptionrequest__user=user,
            adoptionrequest__adoption_status='Approved'
        ).distinct()

        # Favorite pets
        context['favorite_pets'] = Pets.objects.filter(
            petuser__user=user,
            petuser__is_favorite=True
        ).distinct()
        
        # User-added pets /// only shown to the user himself
        context['user_added_pets'] = Pets.objects.filter(added_by=user)

        return context


    
class AdoptRequest(LoginRequiredMixin, ListView):  #to return to the user all of his adoption requests
    model=AdoptionRequest
    template_name='profile.html'
    context_object_name = 'requests'

    def get_queryset(self):
        return AdoptionRequest.objects.filter(user=self.request.user).order_by('-requested_at')


@login_required
def adopt_pet(request, pet_id):   #to allow the user to make an adoption request
    pet = get_object_or_404(Pets, id=pet_id)

    if AdoptionRequest.objects.filter(user=request.user, pet=pet).exists():
        messages.warning(request, f"You have already submitted a request for {pet.breed} {pet.type}.")
        return redirect('all-pets')
    
    if request.method == 'POST':
        form = AdoptionRequestForm(request.POST)
        if form.is_valid():
            adoption = form.save(commit=False)
            adoption.user = request.user
            adoption.pet = pet
            adoption.adoption_status = 'Pending'
            adoption.save()
            messages.success(request, f'Your adoption request for {pet.breed}, {pet.type} has been submitted!')
            return redirect('all-pets')
    else:
        form = AdoptionRequestForm()

    return render(request, 'adopt_pet.html', {'form': form, 'pet': pet})    


@login_required
def delete_adoption_request(request, request_id):      #to allow the user to delete the adoption request
    adoption_request = get_object_or_404(AdoptionRequest, id=request_id, user=request.user)
    adoption_request.delete()
    messages.success(request, "Your adoption request has been deleted.")
    return redirect('profile') 

@login_required
def toggle_favorite(request, pet_id):
    pet = get_object_or_404(Pets, id=pet_id)
    
    pet_user, created = PetUser.objects.get_or_create(user=request.user, pet=pet)
    pet_user.is_favorite = not pet_user.is_favorite  # toggle favorite
    pet_user.save()
    
    return redirect('all-pets')

@login_required
def name_pet_inline(request, adoption_id):
    adoption = get_object_or_404(
        AdoptionRequest, id=adoption_id, user=request.user, adoption_status='Approved'
    )

    if request.method == 'POST':
        pet_name = request.POST.get('pet_name')
        if pet_name:
            adoption.pet_name = pet_name
            adoption.save()
            return redirect('my-pets')

@login_required
def pet_detail(request, pet_id):
    pet = get_object_or_404(Pets, id=pet_id)
    adoption_request_exists = AdoptionRequest.objects.filter(user=request.user, pet=pet).exists()
    return render(request, 'pet_detail.html', {
        'pet': pet,
        'adoption_request_exists': adoption_request_exists
    })


class AddPetView(LoginRequiredMixin, CreateView):
    model = Pets
    form_class = UserPetForm
    template_name = 'add_pet.html'
    success_url = reverse_lazy('my-pets')

    def form_valid(self, form):
        pet = form.save(commit=False)
        pet.added_by = self.request.user  # private pet
        pet.save()
        return super().form_valid(form)

petsadoption/pets_app/templates/add_pet.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/add_pet.css' %}">
{% endblock %}

{% block content %}
<div class="form-container">
    <h2>Add Your Pet</h2>
    <span style='font-size:13px'>* Note: This pet will only be visible to you, it can't be seen by other users. </span>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add Pet</button>
    </form>
</div>
{% endblock %}

petsadoption/pets_app/templates/adopt_pet.html
{% extends 'base.html' %}
{% load static %}

{%block head%}
<link rel='stylesheet' href={%static 'css/adoption_request.css'%} />
{%endblock%}
{% block content %}
<div class="adopt-form-container">
  <h2>Adoption Request for {{pet.breed}} {{ pet.type }}</h2>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit Request</button>
  </form>
</div>
{% endblock %}

petsadoption/pets_app/templates/all_pets.html
{% extends 'base.html'%}
{%load static%}

{%block head%}
    <link rel='stylesheet' href="{%static 'css/all_pets.css'%}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
    

{%endblock%}
{%block content%}
{% if messages %}
        {% for message in messages %}
            <script>
                alert("{{ message }}");
            </script>
        {% endfor %}
    {% endif %}
{%if pets%}
    <h2 class="allpets-h2">Explore All of Our Lovely Pets</h2>
    <form method="GET" class="filter-form">
    <label for="pet_type">Filter by Type:</label>
        <select name="pet_type" id="pet_type" onchange="this.form.submit()">
            <option value="all">All</option>
            {% for t in types %}
                <option value="{{ t }}" {% if selected_type == t %}selected{% endif %}>{{ t }}</option>
            {% endfor %}
        </select>
    </form>
    <div class="card-container"> 
        {%for pet in pets%}
                <div class="pet-cards">
                    <img src= "{{pet.photo.url}}"/>
                    <h4>Type: <span> {{pet.type}} <span> </h4> 
                    <h4>Breed: <span> {{pet.breed}} </span> </h4>
                    <h4>Availablity: <span>{{pet.is_available}} </span> </h4>
                    <div class="pets-card-btn-container">
                        <button  class="pets-card-btn1" onclick="location.href='{% url 'adopt_pet' pet.id %}'">Apply for adoption</button>
                        <button class="pets-card-btn2" onclick="location.href='{% url 'toggle_fav' pet.id %}'">
                            {% if pet.id in favorite_pet_ids %}
                                Remove from Fav
                            {% else %}
                                Add to Fav
                            {% endif %}
                        </button>

                    </div>
                </div>
        {%endfor%}
    </div>       
{%endif%}                  
{%endblock%}

petsadoption/pets_app/templates/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel='stylesheet' href="{% static 'css/base.css'%}" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <nav>
            <ul class='navbar'>
                {%if user.is_authenticated%}
                <li><a href="{% url 'home'%}" class="{% if request.resolver_match.url_name == 'home' %}selected{% endif %}">home</a></li>
                <li><a href="{% url 'all-pets'%}" class="{% if request.resolver_match.url_name == 'all-pets' %}selected{% endif %}">all pets</a></li>
                <li><a href="{% url 'my-pets'%}" class="{% if request.resolver_match.url_name == 'my-pets' %}selected{% endif %}">my pets</a></li>
                <li><a href="{% url 'profile'%}" class="{% if request.resolver_match.url_name == 'profile' %}selected{% endif %}">profile</a></li>
                
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                <li><button type="submit" class="formbtn">Logout</button></li>
                </form>
                {% else %}
                <li><a href="{% url 'landing' %}#about-us">about us</a></li>
                <li><a href="{% url 'signup'%}">signup</a></li>
                <li><a href="{% url 'login'%}">login</a></li>
                {% endif %}
            </ul>
      </nav>
        {%block head%}

        {% endblock %}
    </head>
    
  
    <body>
            {%block content%}
            {%endblock%}

            {%block content2%}
            {%endblock%}


    
    </body>
</html>    
    
    

petsadoption/pets_app/templates/home.html
{% extends 'base.html'%}
{%load static%}

{%block head%}
<link rel='stylesheet' href="{%static 'css/home.css'%}"/>
<script src="https://unpkg.com/@lottiefiles/lottie-player@1.5.7/dist/lottie-player.js"></script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
{%endblock%}

{%block content%}
<div class='main-home-container'>
    <div class='first-block'>
        <div class='home-welcome-msg'>
            <h1> Hello, {{user.first_name}}</h1>
        </div>
        <lottie-player
            src="{% static 'animation/home_page_animation.json' %}"
            background="transparent"
            speed="1"
            class='lottie'
            loop
            autoplay>
        </lottie-player>
    </div>

</div>    
{%endblock%}

petsadoption/pets_app/templates/landing_page.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
    <link rel='stylesheet' href="{%static 'css/landing.css'%}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Cursive:wght@400..700&display=swap" rel="stylesheet">
    <script src="https://unpkg.com/@lottiefiles/lottie-player@1.5.7/dist/lottie-player.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">

{% endblock %}

{% block content %}
    <div class="main-landing-container">
    <div class='first-row'>  
        <div class='animation'>  
            <lottie-player
            class="dog-animation"
            src="{% static 'animation/dog_landing.json' %}"
            background="transparent"
            speed="1"
            style="width: 400px; height: 220px;"
            loop
            autoplay>
        </lottie-player>

        </div>
        <div class="welcomeText">
            <h1>WELCOME TO PawPal</h1>
            <p> where every paw deserves a home</p>
        </div>
    </div>

    <div class='second-row' id="about-us">
        <h1> about us </h1>
        <p> At PawPal, we believe every pet deserves a loving home, and every human deserves a loyal companion! 🐶🐱 <br/>
        Our platform makes finding your perfect furry friend simple, fun, and heartwarming.  </p>
        <strong>Browse adorable pets, learn their stories, and start your adoption journey today. Because sometimes, love comes with paws! </strong>

        <div class='ready-text'>
        <p> 
                Ready to start your adoption journey?
                <span >
                   <a href="{% url 'signup'%}" style="color: orange; font-weight:bold;"> Create an account </a>
                </span> 
                or 
                <span >
                    <a href="{% url 'login'%}" style="color: orange; font-weight:bold;" >log in</a>
                </span> 
                to join our PawPal family!  
            </p>
        </div>
    </div>

</div>
{% endblock %}

petsadoption/pets_app/templates/my_pets.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel='stylesheet' href="{% static 'css/my_pets.css' %}"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Gravitas+One&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="mypets-mainConatiner"> 
    <a href="{% url 'add-pet' %}" class="add-pet-btn">+ Add Your Own Pet</a>
    <div class="section-title">
        <span>My Adopted Pets</span>
    </div>
    <div class="cards_container">
        {% if adopted_pets %}
            {% for pet in adopted_pets %}
                <div class="mypets-card" >
                        <img src='{{pet.photo.url}}'/>
                        <div class="card-content">
                            <span>{{ pet.breed }} {{ pet.type }}</span>
                        {% for adoption in pet.adoptionrequest_set.all %}
                        {% if adoption.user == request.user and adoption.adoption_status == 'Approved' %}
                            {% if adoption.pet_name %}
                                <p>Your Pet’s Name Is <strong class='pet-name'>{{ adoption.pet_name }} </strong></p>
                            {% else %}
                                <form method="POST" action="{% url 'name-pet-inline' adoption.id %}" class="inline-form">
                                    {% csrf_token %}
                                    <input type="text" name="pet_name" placeholder="Enter a name" required class="pet-name-input">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </form>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h3>No adopted pets yet</h3>
        {% endif %}
    </div>


   <div class="section-title">
        <span>My Favorite Pets</span>
    </div>
    <div class="fav-cards-container">
        {% if favorite_pets %}
            {% for pet in favorite_pets %}
                <div class="mypets-fav-card">
                    <a href="{% url 'pet-detail' pet.id %}">
                        <img src='{{ pet.photo.url }}'/>
                        <div class="fav-card-content">
                            <span>{{ pet.breed }} {{ pet.type }}</span>
                        </div>
                    </a>
                </div>
            {% endfor %}
        {% else %}
            <p>You have no favorite pets yet.</p>
        {% endif %}
    </div>


    <div class="section-title">
        <span>My Personal pets</span>
    </div>
    <div class="fav-cards-container">
        {% if user_added_pets %}
        {% for pet in user_added_pets %}
            <div class="mypets-fav-card">
                <img src="{{ pet.photo.url }}" alt="{{ pet.pet_name|default:pet.breed }}">
                <div class="card-content">
                    <span>{{ pet.pet_name}}</span>
                    <span>{{ pet.pet_name}} {{ pet.type }}</span>
                    <p>{{ pet.description }}</p>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>You haven’t added any pets yet.</p>
    {% endif %}
    </div>

</div>
{% endblock %}

petsadoption/pets_app/templates/pet_detail.html
{% extends 'base.html' %}
{% load static %}


{%block head%}
<link rel='stylesheet' href="{%static 'css/pet_detail.css'%}" />
{%endblock%}
{% block content %}
<div class="pet-detail-container">
    <img src="{{ pet.photo.url }}" alt="{{ pet.type }}" />
    <h2>{{ pet.type }} - {{ pet.breed }}</h2>
    <p>Availability: {{ pet.is_available }}</p>
    <p>{{pet.is_favorite}} <p>
    {% if pet.description %}
        <p>Description: {{ pet.description }}</p>
    {% endif %}

    {% if not adoption_request_exists %}
        <button onclick="location.href='{% url 'adopt_pet' pet.id %}'">Apply for Adoption</button>
    {% else %}
        <p>You have already submitted an adoption request for this pet.</p>
    {% endif %}
</div>
{% endblock %}

petsadoption/pets_app/templates/profile.html
{%extends 'base.html'%}
{%load static%}

{%block head%}
    <link rel='stylesheet' href="{%static 'css/profile.css'%}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gravitas+One&display=swap" rel="stylesheet">
{%endblock%}

{%block content%}

<div class='main-container'>
    <div style="display:flex ; flex-direction : column">
        <h1 class='profile-header'> your adoption requests</h1> 
            <div class='adoption-req'>
                <table>
                    <tr>
                        <th>PET</th>
                        <th>REQUEST STATUS</th>
                        <th>REQUEST DATE</th>
                        <th>ACTION</th>
                    </tr>
                    {% for req in requests %}
                    <tr>
                        <td>{{ req.pet.type }}, {{ req.pet.breed }}</td>
                        <td>{{ req.adoption_status }}</td>
                        <td>{{req.requested_at}} </td>
                        <td>
                            <form method="POST" action="{% url 'delete_request' req.id %}">
                                {% csrf_token %}
                                {% if req.adoption_status == "Pending" or req.adoption_status == "Rejected" %}
                                    <button type="submit" onclick="return confirm('Are you sure you want to delete this request?');">
                                        Delete Request
                                    </button>
                                {% endif %}
                            </form>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="3">No adoption requests yet.</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <p style="margin: 5px 28px; color: chocolate ; font-size:13px"> *When a request is approved the pet will be added to your adopted pets in (my pets) page </p>
    </div>
    <div style="display:flex ; flex-direction : column ">
        <h1 class='profile-header'>profile information</h1> 
        <div class='form-container'> 
            <form method="POST" >
                {% csrf_token %}
                {{form}}
                <button type="submit">Save Changes</button>
            </form>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div> 
    </div>
    
</div>
  

{%endblock%}